// Generated by tools/gen_kbmatrix.py from "VICE-GTK3-Keymap v0.91 beta.vkm".
// Do not edit by hand -- regenerate with:
//   tools/gen_kbmatrix.py "VICE-GTK3-Keymap v0.91 beta.vkm"
#include <cstdint>

// row < 0 means "this scancode has no C64 matrix mapping". `shift` carries the
// raw vkm shiftflag bits (see VICE's enum shift_type in vice-3.10/src/keymap.h):
// bit 0 VIRTUAL_SHIFT, bit 1 LEFT_SHIFT, bit 2 RIGHT_SHIFT, bit 3 ALLOW_SHIFT,
// bit 4 DESHIFT_SHIFT, bit 6 SHIFT_LOCK. KonsoolKB.cpp applies these the same
// way VICE's keyboard.c does (see keyboard_key_pressed_matrix /
// keyboard_latch_modifier_states).
struct KbMatrixEntry {
    int8_t  row;
    int8_t  col;
    uint8_t shift;
};

// Matrix position of the two real shift keys, and which one absorbs a forced
// ("virtual") shift from another key's VIRTUAL_SHIFT bit -- from this keymap's
// "!LSHIFT 1 7", "!RSHIFT 6 4" and
// "!VSHIFT RSHIFT" directives.
constexpr int8_t LSHIFT_ROW        = 1;
constexpr int8_t LSHIFT_COL        = 7;
constexpr int8_t RSHIFT_ROW        = 6;
constexpr int8_t RSHIFT_COL        = 4;
constexpr bool    VSHIFT_IS_RSHIFT = true;

static const KbMatrixEntry kb_matrix[128] = {
    { -1, -1, 0x00 },  // 00
    {  7,  7, 0x08 },  // 01 : ESC
    {  7,  0, 0x00 },  // 02 : 1 (1/exclam)
    {  7,  3, 0x00 },  // 03 : 2 (2/at)
    {  1,  0, 0x00 },  // 04 : 3 (3/numbersign)
    {  1,  3, 0x00 },  // 05 : 4 (4/dollar)
    {  2,  0, 0x00 },  // 06 : 5 (5/percent)
    {  2,  3, 0x00 },  // 07 : 6 (6/asciicircum)
    {  3,  0, 0x00 },  // 08 : 7 (7/ampersand)
    {  3,  3, 0x00 },  // 09 : 8 (8/asterisk)
    {  4,  0, 0x00 },  // 0a : 9 (9/parenleft)
    {  4,  3, 0x00 },  // 0b : 0 (0/parenright)
    {  5,  3, 0x00 },  // 0c : MINUS (minus/underscore)
    {  6,  5, 0x00 },  // 0d : EQUAL (equal/plus)
    {  0,  0, 0x08 },  // 0e : BACKSPACE
    { -1, -1, 0x00 },  // 0f
    {  7,  6, 0x08 },  // 10 : Q (q/Q)
    {  1,  1, 0x08 },  // 11 : W (w/W)
    {  1,  6, 0x08 },  // 12 : E (e/E)
    {  2,  1, 0x08 },  // 13 : R (r/R)
    {  2,  6, 0x08 },  // 14 : T (t/T)
    {  3,  1, 0x08 },  // 15 : Y (y/Y)
    {  3,  6, 0x08 },  // 16 : U (u/U)
    {  4,  1, 0x08 },  // 17 : I (i/I)
    {  4,  6, 0x08 },  // 18 : O (o/O)
    {  5,  1, 0x08 },  // 19 : P (p/P)
    {  5,  5, 0x01 },  // 1a : LEFTBRACE
    {  6,  2, 0x01 },  // 1b : RIGHTBRACE
    {  0,  1, 0x08 },  // 1c : ENTER
    {  7,  2, 0x08 },  // 1d : LEFTCTRL
    {  1,  2, 0x08 },  // 1e : A (a/A)
    {  1,  5, 0x08 },  // 1f : S (s/S)
    {  2,  2, 0x08 },  // 20 : D (d/D)
    {  2,  5, 0x08 },  // 21 : F (f/F)
    {  3,  2, 0x08 },  // 22 : G (g/G)
    {  3,  5, 0x08 },  // 23 : H (h/H)
    {  4,  2, 0x08 },  // 24 : J (j/J)
    {  4,  5, 0x08 },  // 25 : K (k/K)
    {  5,  2, 0x08 },  // 26 : L (l/L)
    {  6,  2, 0x00 },  // 27 : SEMICOLON (semicolon/colon)
    {  3,  0, 0x01 },  // 28 : APOSTROPHE (apostrophe/quotedbl)
    {  7,  1, 0x00 },  // 29 : GRAVE (grave/asciitilde)
    {  1,  7, 0x02 },  // 2a : LEFTSHIFT
    {  6,  0, 0x00 },  // 2b : BACKSLASH (backslash/bar)
    {  1,  4, 0x08 },  // 2c : Z (z/Z)
    {  2,  7, 0x08 },  // 2d : X (x/X)
    {  2,  4, 0x08 },  // 2e : C (c/C)
    {  3,  7, 0x08 },  // 2f : V (v/V)
    {  3,  4, 0x08 },  // 30 : B (b/B)
    {  4,  7, 0x08 },  // 31 : N (n/N)
    {  4,  4, 0x08 },  // 32 : M (m/M)
    {  5,  7, 0x00 },  // 33 : COMMA (comma/less)
    {  5,  4, 0x00 },  // 34 : DOT (period/greater)
    {  6,  7, 0x00 },  // 35 : SLASH (slash/question)
    {  6,  4, 0x04 },  // 36 : RIGHTSHIFT
    { -1, -1, 0x00 },  // 37
    { -1, -1, 0x00 },  // 38
    {  7,  4, 0x08 },  // 39 : SPACE
    { -1, -1, 0x00 },  // 3a
    {  0,  4, 0x08 },  // 3b : F1 (F1/F2)
    {  0,  5, 0x08 },  // 3c : F2 (F3/F4)
    {  0,  6, 0x08 },  // 3d : F3 (F5/F6)
    {  0,  3, 0x08 },  // 3e : F4 (F7/F8)
    { -1, -1, 0x00 },  // 3f
    { -1, -1, 0x00 },  // 40
    { -1, -1, 0x00 },  // 41
    { -1, -1, 0x00 },  // 42
    { -1, -1, 0x00 },  // 43
    { -1, -1, 0x00 },  // 44
    { -1, -1, 0x00 },  // 45
    { -1, -1, 0x00 },  // 46
    { -1, -1, 0x00 },  // 47
    {  0,  7, 0x01 },  // 48 : ESCAPED_GREY_UP
    { -1, -1, 0x00 },  // 49
    { -1, -1, 0x00 },  // 4a
    {  0,  2, 0x01 },  // 4b : ESCAPED_GREY_LEFT
    { -1, -1, 0x00 },  // 4c
    {  0,  2, 0x08 },  // 4d : ESCAPED_GREY_RIGHT
    { -1, -1, 0x00 },  // 4e
    { -1, -1, 0x00 },  // 4f
    {  0,  7, 0x08 },  // 50 : ESCAPED_GREY_DOWN
    { -1, -1, 0x00 },  // 51
    { -1, -1, 0x00 },  // 52
    { -1, -1, 0x00 },  // 53
    { -1, -1, 0x00 },  // 54
    { -1, -1, 0x00 },  // 55
    { -1, -1, 0x00 },  // 56
    { -1, -1, 0x00 },  // 57
    { -1, -1, 0x00 },  // 58
    { -1, -1, 0x00 },  // 59
    { -1, -1, 0x00 },  // 5a
    {  7,  5, 0x08 },  // 5b : ESCAPED_LEFTMETA
    { -1, -1, 0x00 },  // 5c
    { -1, -1, 0x00 },  // 5d
    { -1, -1, 0x00 },  // 5e
    { -1, -1, 0x00 },  // 5f
    { -1, -1, 0x00 },  // 60
    { -1, -1, 0x00 },  // 61
    { -1, -1, 0x00 },  // 62
    { -1, -1, 0x00 },  // 63
    { -1, -1, 0x00 },  // 64
    { -1, -1, 0x00 },  // 65
    { -1, -1, 0x00 },  // 66
    { -1, -1, 0x00 },  // 67
    { -1, -1, 0x00 },  // 68
    { -1, -1, 0x00 },  // 69
    { -1, -1, 0x00 },  // 6a
    { -1, -1, 0x00 },  // 6b
    { -1, -1, 0x00 },  // 6c
    { -1, -1, 0x00 },  // 6d
    { -1, -1, 0x00 },  // 6e
    { -1, -1, 0x00 },  // 6f
    { -1, -1, 0x00 },  // 70
    { -1, -1, 0x00 },  // 71
    { -1, -1, 0x00 },  // 72
    { -1, -1, 0x00 },  // 73
    { -1, -1, 0x00 },  // 74
    { -1, -1, 0x00 },  // 75
    { -1, -1, 0x00 },  // 76
    { -1, -1, 0x00 },  // 77
    { -1, -1, 0x00 },  // 78
    { -1, -1, 0x00 },  // 79
    { -1, -1, 0x00 },  // 7a
    { -1, -1, 0x00 },  // 7b
    { -1, -1, 0x00 },  // 7c
    { -1, -1, 0x00 },  // 7d
    { -1, -1, 0x00 },  // 7e
    { -1, -1, 0x00 },  // 7f
};

static const KbMatrixEntry kb_matrix_shift[128] = {
    { -1, -1, 0x00 },  // 00
    {  7,  7, 0x08 },  // 01 : ESC
    {  7,  0, 0x01 },  // 02 : 1 (1/exclam)
    {  5,  6, 0x10 },  // 03 : 2 (2/at)
    {  1,  0, 0x01 },  // 04 : 3 (3/numbersign)
    {  1,  3, 0x01 },  // 05 : 4 (4/dollar)
    {  2,  0, 0x01 },  // 06 : 5 (5/percent)
    {  6,  6, 0x10 },  // 07 : 6 (6/asciicircum)
    {  2,  3, 0x01 },  // 08 : 7 (7/ampersand)
    {  6,  1, 0x10 },  // 09 : 8 (8/asterisk)
    {  3,  3, 0x01 },  // 0a : 9 (9/parenleft)
    {  4,  0, 0x01 },  // 0b : 0 (0/parenright)
    {  5,  6, 0x01 },  // 0c : MINUS (minus/underscore)
    {  5,  0, 0x10 },  // 0d : EQUAL (equal/plus)
    {  0,  0, 0x08 },  // 0e : BACKSPACE
    { -1, -1, 0x00 },  // 0f
    {  7,  6, 0x01 },  // 10 : Q (q/Q)
    {  1,  1, 0x01 },  // 11 : W (w/W)
    {  1,  6, 0x01 },  // 12 : E (e/E)
    {  2,  1, 0x01 },  // 13 : R (r/R)
    {  2,  6, 0x01 },  // 14 : T (t/T)
    {  3,  1, 0x01 },  // 15 : Y (y/Y)
    {  3,  6, 0x01 },  // 16 : U (u/U)
    {  4,  1, 0x01 },  // 17 : I (i/I)
    {  4,  6, 0x01 },  // 18 : O (o/O)
    {  5,  1, 0x01 },  // 19 : P (p/P)
    {  5,  5, 0x01 },  // 1a : LEFTBRACE
    {  6,  2, 0x01 },  // 1b : RIGHTBRACE
    {  0,  1, 0x08 },  // 1c : ENTER
    {  7,  2, 0x08 },  // 1d : LEFTCTRL
    {  1,  2, 0x01 },  // 1e : A (a/A)
    {  1,  5, 0x01 },  // 1f : S (s/S)
    {  2,  2, 0x01 },  // 20 : D (d/D)
    {  2,  5, 0x01 },  // 21 : F (f/F)
    {  3,  2, 0x01 },  // 22 : G (g/G)
    {  3,  5, 0x01 },  // 23 : H (h/H)
    {  4,  2, 0x01 },  // 24 : J (j/J)
    {  4,  5, 0x01 },  // 25 : K (k/K)
    {  5,  2, 0x01 },  // 26 : L (l/L)
    {  5,  5, 0x10 },  // 27 : SEMICOLON (semicolon/colon)
    {  7,  3, 0x01 },  // 28 : APOSTROPHE (apostrophe/quotedbl)
    {  7,  1, 0x00 },  // 29 : GRAVE (grave/asciitilde)
    {  1,  7, 0x02 },  // 2a : LEFTSHIFT
    {  6,  0, 0x08 },  // 2b : BACKSLASH (backslash/bar)
    {  1,  4, 0x01 },  // 2c : Z (z/Z)
    {  2,  7, 0x01 },  // 2d : X (x/X)
    {  2,  4, 0x01 },  // 2e : C (c/C)
    {  3,  7, 0x01 },  // 2f : V (v/V)
    {  3,  4, 0x01 },  // 30 : B (b/B)
    {  4,  7, 0x01 },  // 31 : N (n/N)
    {  4,  4, 0x01 },  // 32 : M (m/M)
    {  5,  7, 0x01 },  // 33 : COMMA (comma/less)
    {  5,  4, 0x01 },  // 34 : DOT (period/greater)
    {  6,  7, 0x01 },  // 35 : SLASH (slash/question)
    {  6,  4, 0x04 },  // 36 : RIGHTSHIFT
    { -1, -1, 0x00 },  // 37
    { -1, -1, 0x00 },  // 38
    {  7,  4, 0x08 },  // 39 : SPACE
    { -1, -1, 0x00 },  // 3a
    {  0,  4, 0x01 },  // 3b : F1 (F1/F2)
    {  0,  5, 0x01 },  // 3c : F2 (F3/F4)
    {  0,  6, 0x01 },  // 3d : F3 (F5/F6)
    {  0,  3, 0x01 },  // 3e : F4 (F7/F8)
    { -1, -1, 0x00 },  // 3f
    { -1, -1, 0x00 },  // 40
    { -1, -1, 0x00 },  // 41
    { -1, -1, 0x00 },  // 42
    { -1, -1, 0x00 },  // 43
    { -1, -1, 0x00 },  // 44
    { -1, -1, 0x00 },  // 45
    { -1, -1, 0x00 },  // 46
    { -1, -1, 0x00 },  // 47
    {  0,  7, 0x01 },  // 48 : ESCAPED_GREY_UP
    { -1, -1, 0x00 },  // 49
    { -1, -1, 0x00 },  // 4a
    {  0,  2, 0x01 },  // 4b : ESCAPED_GREY_LEFT
    { -1, -1, 0x00 },  // 4c
    {  0,  2, 0x08 },  // 4d : ESCAPED_GREY_RIGHT
    { -1, -1, 0x00 },  // 4e
    { -1, -1, 0x00 },  // 4f
    {  0,  7, 0x08 },  // 50 : ESCAPED_GREY_DOWN
    { -1, -1, 0x00 },  // 51
    { -1, -1, 0x00 },  // 52
    { -1, -1, 0x00 },  // 53
    { -1, -1, 0x00 },  // 54
    { -1, -1, 0x00 },  // 55
    { -1, -1, 0x00 },  // 56
    { -1, -1, 0x00 },  // 57
    { -1, -1, 0x00 },  // 58
    { -1, -1, 0x00 },  // 59
    { -1, -1, 0x00 },  // 5a
    {  7,  5, 0x08 },  // 5b : ESCAPED_LEFTMETA
    { -1, -1, 0x00 },  // 5c
    { -1, -1, 0x00 },  // 5d
    { -1, -1, 0x00 },  // 5e
    { -1, -1, 0x00 },  // 5f
    { -1, -1, 0x00 },  // 60
    { -1, -1, 0x00 },  // 61
    { -1, -1, 0x00 },  // 62
    { -1, -1, 0x00 },  // 63
    { -1, -1, 0x00 },  // 64
    { -1, -1, 0x00 },  // 65
    { -1, -1, 0x00 },  // 66
    { -1, -1, 0x00 },  // 67
    { -1, -1, 0x00 },  // 68
    { -1, -1, 0x00 },  // 69
    { -1, -1, 0x00 },  // 6a
    { -1, -1, 0x00 },  // 6b
    { -1, -1, 0x00 },  // 6c
    { -1, -1, 0x00 },  // 6d
    { -1, -1, 0x00 },  // 6e
    { -1, -1, 0x00 },  // 6f
    { -1, -1, 0x00 },  // 70
    { -1, -1, 0x00 },  // 71
    { -1, -1, 0x00 },  // 72
    { -1, -1, 0x00 },  // 73
    { -1, -1, 0x00 },  // 74
    { -1, -1, 0x00 },  // 75
    { -1, -1, 0x00 },  // 76
    { -1, -1, 0x00 },  // 77
    { -1, -1, 0x00 },  // 78
    { -1, -1, 0x00 },  // 79
    { -1, -1, 0x00 },  // 7a
    { -1, -1, 0x00 },  // 7b
    { -1, -1, 0x00 },  // 7c
    { -1, -1, 0x00 },  // 7d
    { -1, -1, 0x00 },  // 7e
    { -1, -1, 0x00 },  // 7f
};
